### ISSUE TITLE
Add link back to the home page from sub pages

### ISSUE THREAD

**Issue by bgrins** [mozilla/firefox-browser-architecture#14]
There's no link back to the home page right now from https://mozilla.github.io/firefox-browser-architecture/text/0002-extracting-necko.html

**Comment by joewalker** [comment]
I tried this: 6d34d859 which just adds a couple of links to `..`. Simple, but then the links appear on the homepage too.

I tried adding `_layout/index.html` without the links and then directed the `README.md` to use that instead of the default:

    ---
    title: index
    layout: index
    ---

But this 404s on links to the homepage (similar to https://github.com/mozilla/firefox-browser-architecture/pull/19#discussion_r135233173).

My best fix so far is to require all markdown files except README.md to specify a non-default layout, which is kind of a terrible fix.

Suggestions welcome.

**Comment by joewalker** [comment]
Fixed by #22
